### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by Loongphy** [sparticleinc/chatgpt-google-summary-extension#37]
**Describe the bug**
The console reported an error and affected the normal display of page content. Currently, the tables in [Feishu](https://www.feishu.cn/) documents are affected.

```js
content-script.js:50044 
       Uncaught TypeError: Cannot read properties of null (reading '0')
    at content-script.js:50044:3234
    at content-script.js:50095:239
```

```js
V2.includes("github.com") ? "github" : V2.match(gb)[0]`, N1 = Xr[tn];

async function fb(n) { var d, g, c; let { question: u, siteConfig: e, transcript: t, langOptionsWithLink: r } = n; document.querySelector("div.glarity--container") && ((d = document.querySelector("div.glarity--container")) == null || d.remove()); let i = document.createElement("div"); i.className = "glarity--container"; let o = await au(), l; if (o.theme === "auto" ? l = Qu() : l = o.theme, l === "dark" ? i.classList.add("gpt--dark") : i.classList.add("gpt--light"), tn === "pubmed") { i.classList.add("glarity--chatgpt--pubmed"); let f = V1(e.extabarContainerQuery || []); console.log("appendContainer", f), f == null || f.prepend(i) } else if (tn === "yahooJpNews") { i.classList.add("glarity--chatgpt--yahoonews"); let f = V1(e.extabarContainerQuery || []); f == null || f.prepend(i) } else if (tn === "newspicks") { i.classList.add("glarity--chatgpt--newspicks"); let f = V1(e.extabarContainerQuery || []); f == null || f.prepend(i) } else if (tn === "nikkei") { i.classList.add("glarity--chatgpt--nikkei"); let f = V1(e.extabarContainerQuery || []); f == null || f.prepend(i) } else if (tn === "github") { i.classList.add("glarity--chatgpt--github"); let f = V1(e.extabarContainerQuery || []); f == null || f.prepend(i) } else if (tn === "youtube") i.classList.add("glarity--chatgpt--youtube"), ot("#secondary.style-scope.ytd-watch-flexy").then(() => { var f; (f = document.querySelector("#secondary.style-scope.ytd-watch-flexy")) == null || f.prepend(i) }); else { let f = V1(e.sidebarContainerQuery); if (console.log("siderbarContainer", f, (g = document.querySelector("#center_col")) == null ? void 0 : g.nextSibling), f) f.prepend(i); else if (e.extabarContainerQuery && ((c = document.querySelector("#center_col")) != null && c.nextSibling)) { i.classList.add("glarity--full-container"); let v = V1(e.extabarContainerQuery); v && v.appendChild(i) } else { i.classList.add("sidebar--free"); let v = V1(e.appendContainerQuery); v && v.appendChild(i) } } Fn(a0(Gc, { question: u, transcript: t, siteConfig: e, langOptionsWithLink: r, triggerMode: o.triggerMode || "always" }), i) }

async function T7() { let n = await $r(!0); n && fb(n) }

async function $r(n) { var i, o, l, d, g, c; let u = window.navigator.language, e = await au(), t = await Qo(); if (console.log("providerConfigs", t), tn === "pubmed") { if (!/(pubmed.ncbi.nlm.nih.gov/\d{8,})|(ncbi.nlm.nih.gov/pmc/articles/\w+)/.test(location.href)) return null; let f = document.title || "", v = location.href, y = V1(N1.contentContainerQuery || []); document.querySelector("div#abstract-1 + #body-1"); let E; if (y) E = y == null ? void 0 : y.textContent; else { let D = ["div#abstract-1", "#body-1", "div#sec2", "div#sec3", "div#sec4", "div#sec5", "div#sec6", "div#sec7", "div#sec8", "div#sec9", "div#sec10"]; for (let z = 0; z < D.length; z++) { let P = (i = document.querySelector(D[z])) == null ? void 0 : i.textContent; P && (E = E + " " + P) } } if (console.log("articleText", E), !E) return null; let S = jn(E, t.provider); console.log("content", S); let w = `` } return null }
```

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.1344
 - Browser: Edge110.0.1587.63

**Comment by givebest** [comment]
May I ask what version you are using? @Loongphy

**Comment by givebest** [comment]
I have fixed this issue
Now you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages) and adding it manually (https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome).

**Comment by Loongphy** [comment]
The problem has been resolved. Thank you for your quick fix and excellent work.
